// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/acesso-negado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acesso-negado">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/acesso-negado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/depositantes/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/depositantes/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/depositantes/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/depositantes/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/depositantes/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/depositantes/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/depositantes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/depositantes">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/depositantes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/enderecos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/enderecos">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/enderecos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/integracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/integracoes">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/integracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/produtos/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/produtos/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/produtos/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/produtos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/produtos/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/produtos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/produtos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/produtos">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/produtos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/transportadoras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/transportadoras">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/transportadoras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/configuracoes/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes/usuarios">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/conciliacao-pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/conciliacao-pedidos">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/conciliacao-pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/inventarios/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/inventarios/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/inventarios/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/inventarios/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/inventarios/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/inventarios/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/inventarios/pendencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/inventarios/pendencias">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/inventarios/pendencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/movimentacao-interna/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/movimentacao-interna">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/movimentacao-interna/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/protocolos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/protocolos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/protocolos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/estoque/saldo-inicial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque/saldo-inicial">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/estoque/saldo-inicial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/conferencia/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/conferencia/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/conferencia/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/conferencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/conferencia">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/conferencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/conferidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/conferidos">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/conferidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/separacao/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/separacao/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/separacao/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/separacao/lote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/separacao/lote">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/separacao/lote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/separacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expedicao/separacao">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/separacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/nfe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nfe">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/nfe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/recebimento/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recebimento/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/recebimento/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/recebimento/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recebimento/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/recebimento/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/recebimento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recebimento">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/recebimento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/relatorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relatorios">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/relatorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/romaneio/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/romaneio/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/romaneio/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/romaneio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/romaneio">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/romaneio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/suporte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suporte">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/suporte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/test-sticky/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-sticky">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/test-sticky/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/yms/agendamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yms/agendamentos">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/yms/agendamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/yms/docas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yms/docas">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/yms/docas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/yms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yms">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/yms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/conferencia/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/conferencia/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/conferencia/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/conferencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/conferencia">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/conferencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/enderecos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/enderecos/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/enderecos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/enderecos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/enderecos">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/enderecos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/[depositanteId]/[estoqueId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/entrada-manual/[depositanteId]/[estoqueId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/[depositanteId]/[estoqueId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/entrada-manual/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/entrada-manual">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/entrada-manual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/inventarios/[depositanteId]/[estoqueId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/inventarios/[depositanteId]/[estoqueId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/inventarios/[depositanteId]/[estoqueId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/inventarios/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/inventarios/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/inventarios/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/inventarios/geral/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/inventarios/geral/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/inventarios/geral/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/inventarios/geral/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/inventarios/geral">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/inventarios/geral/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/inventarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/inventarios">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/inventarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/[depositanteId]/[estoqueId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/movimentacao-interna/[depositanteId]/[estoqueId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/[depositanteId]/[estoqueId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/movimentacao-interna/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/movimentacao-interna">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/movimentacao-interna/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saida-manual/[depositanteId]/[estoqueId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saida-manual/[depositanteId]/[estoqueId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saida-manual/[depositanteId]/[estoqueId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saida-manual/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saida-manual/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saida-manual/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saida-manual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saida-manual">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saida-manual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/[depositanteId]/[produtoId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saldo-inicial/[depositanteId]/[produtoId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/[depositanteId]/[produtoId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/[depositanteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saldo-inicial/[depositanteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/[depositanteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/estoque/saldo-inicial">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/estoque/saldo-inicial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/inicio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/inicio">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/inicio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/produtos/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/produtos/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/produtos/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/produtos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/produtos/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/produtos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/produtos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/produtos">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/produtos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/recebimento/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/recebimento/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/recebimento/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/recebimento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/recebimento">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/recebimento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/romaneio/[id]/fechar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/romaneio/[id]/fechar">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/romaneio/[id]/fechar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/romaneio/[id]/foto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/romaneio/[id]/foto">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/romaneio/[id]/foto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/romaneio/[id]/visualizar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/romaneio/[id]/visualizar">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/romaneio/[id]/visualizar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/romaneio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/romaneio">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/romaneio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/separacao/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/separacao/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/separacao/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/separacao/nova/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/separacao/nova">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/separacao/nova/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/separacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/separacao">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/separacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/sair/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/sair">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/sair/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(portal)/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/(portal)/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/depositantes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/depositantes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/depositantes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/enderecos/importar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/enderecos/importar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/enderecos/importar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/enderecos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/enderecos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/enderecos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/produtos/importar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/produtos/importar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/produtos/importar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/produtos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/produtos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/produtos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/configuracoes/usuarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracoes/usuarios">> = Specific
  const handler = {} as typeof import("../../../src/app/api/configuracoes/usuarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/sync-bling-xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-bling-xml">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/sync-bling-xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documentos/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documentos/[id]/download">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documentos/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documentos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/ajuste/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/ajuste">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/ajuste/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/conciliacao-pedidos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/conciliacao-pedidos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/conciliacao-pedidos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/entrada-manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/entrada-manual">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/entrada-manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventariar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventariar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventariar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventario-resolver/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventario-resolver">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventario-resolver/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios-gerais/[id]/confirmar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios-gerais/[id]/confirmar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios-gerais/[id]/confirmar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios-gerais/[id]/itens/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios-gerais/[id]/itens/[itemId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios-gerais/[id]/itens/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios-gerais/[id]/relatorio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios-gerais/[id]/relatorio">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios-gerais/[id]/relatorio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios-gerais/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios-gerais/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios-gerais/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios-gerais/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios-gerais">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios-gerais/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios/itens/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios/itens/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios/itens/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/inventarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/inventarios">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/inventarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/movimentacoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/movimentacoes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/movimentacoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/protocolos/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/protocolos/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/protocolos/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/protocolos/lote/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/protocolos/lote/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/protocolos/lote/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/resolver-produto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/resolver-produto">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/resolver-produto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/estoque/saida-manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque/saida-manual">> = Specific
  const handler = {} as typeof import("../../../src/app/api/estoque/saida-manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/anexos/[kind]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/anexos/[kind]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/anexos/[kind]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/danfe-simplificada/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/danfe-simplificada">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/danfe-simplificada/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/danfe-validacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/danfe-validacao">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/danfe-validacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/etiqueta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/etiqueta">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/etiqueta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/nota-fiscal-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/nota-fiscal-preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/nota-fiscal-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/sincronizar-mercado-livre/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/sincronizar-mercado-livre">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/sincronizar-mercado-livre/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/[id]/sincronizar-xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao/[id]/sincronizar-xml">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/[id]/sincronizar-xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/expedicao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expedicao">> = Specific
  const handler = {} as typeof import("../../../src/app/api/expedicao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/alertas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/alertas">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/alertas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/bling/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/bling/oauth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/bling/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/bling/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/bling/oauth/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/bling/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/bling/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/bling/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/bling/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/mercado-livre/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/mercado-livre/oauth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/mercado-livre/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integracoes/mercado-livre/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracoes/mercado-livre/oauth/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integracoes/mercado-livre/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/nfe/importar-saida/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nfe/importar-saida">> = Specific
  const handler = {} as typeof import("../../../src/app/api/nfe/importar-saida/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/nfe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nfe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/nfe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/portal/produtos/[id]/limites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/produtos/[id]/limites">> = Specific
  const handler = {} as typeof import("../../../src/app/api/portal/produtos/[id]/limites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/portal/produtos/exportar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/produtos/exportar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/portal/produtos/exportar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/portal/produtos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/produtos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/portal/produtos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/portal/recebimentos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/recebimentos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/portal/recebimentos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/portal/recebimentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/recebimentos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/portal/recebimentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recebimento/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recebimento/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recebimento/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recebimento/importar-xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recebimento/importar-xml">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recebimento/importar-xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recebimento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recebimento">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recebimento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/relatorios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/relatorios">> = Specific
  const handler = {} as typeof import("../../../src/app/api/relatorios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/romaneio/[id]/foto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/romaneio/[id]/foto">> = Specific
  const handler = {} as typeof import("../../../src/app/api/romaneio/[id]/foto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/romaneio/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/romaneio/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/romaneio/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/romaneio/exportar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/romaneio/exportar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/romaneio/exportar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/romaneio/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/romaneio/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/romaneio/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/romaneio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/romaneio">> = Specific
  const handler = {} as typeof import("../../../src/app/api/romaneio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suporte/chamados/[id]/comentarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suporte/chamados/[id]/comentarios">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suporte/chamados/[id]/comentarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suporte/chamados/[id]/leitura/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suporte/chamados/[id]/leitura">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suporte/chamados/[id]/leitura/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suporte/chamados/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suporte/chamados/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suporte/chamados/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suporte/chamados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suporte/chamados">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suporte/chamados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suporte/notificacoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suporte/notificacoes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suporte/notificacoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(dashboard)/configuracoes/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/configuracoes/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/expedicao/conferencia/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/expedicao/conferencia">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/expedicao/conferencia/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/recebimento/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/recebimento">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/recebimento/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/yms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/yms">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/yms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(mobile)/m/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m">> = Specific
  const handler = {} as typeof import("../../../src/app/(mobile)/m/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(portal)/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/(portal)/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
